name: Terraform CD Apply

on:
    # push:
    #     branches: [main]
    workflow_dispatch:

permissions:
    contents: read
    id-token: write

jobs:
    apply:
        uses: ITAssetManagementSystem/CommonWorkflows/.github/workflows/terraform-apply.yml@main
        with:
            tf_dir: environment/dev
        secrets: inherit
