name: Terraform CD Apply

on:
    # push:
    #     branches: [main]
    workflow_dispatch:

jobs:
    apply:
        uses: ITAssetManagementSystem/CommonWorkflows/.github/workflows/terraform-apply.yml@main
        with:
            tf_dir: environment/dev
        secrets: inherit
