name: InfraService CD - Terraform Apply

on:
  push:
    branches:
      - main
    paths:
      - "InfraService/**"

jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    environment: dev   # ðŸ‘ˆ GitHub environment approval laga sakti ho

    steps:
      - name: Terraform Apply
        uses: ITAssetManagementSystem/CommonWorkflows/.github/actions/terraform-plan@main
        with:
          working_directory: InfraService
          environment: dev
