name: Terraform CI Plan

on:
  pull_request:
    branches: [main]

jobs:
  plan:
    uses: ITAssetManagementSystem/CommonWorkflows/.github/workflows/terraform-plan.yml@main
    with:
      tf_dir: environment/dev
    secrets: inherit
