name: Terraform Plan

on:
  workflow_dispatch:

jobs:
  call-composite:
    runs-on: ubuntu-latest
    steps:
      - name: Call composite action
        uses: ITAssetManagementSystem/CommonWorkflows/.github/actions/terraform-plan@main
        with:
          message: "Hello from composite action caller Nilay!"
